<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DSO.Core.Evoker.Plugins.DemoApi\**" />
    <EmbeddedResource Remove="DSO.Core.Evoker.Plugins.DemoApi\**" />
    <None Remove="DSO.Core.Evoker.Plugins.DemoApi\**" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\DSO.Core.Evoker.Api\DSO.Core.Evoker.Api.csproj" />
    <ProjectReference Include="..\DSO.Core.Evoker.Plugins\DSO.Core.Evoker.Plugins.csproj" />
  </ItemGroup>

</Project>
